<a href="https://colab.research.google.com/github/shivashankarkammari/python/blob/main/Numpy_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [5]:
# Create a null vector of size 10 but the fifth value which is 1

vec = np.zeros(10)
vec[5] = 1
vec


array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [6]:
# Create a vector with values ranging from 10 to 49

val = np.arange(10,50)
val

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [10]:
# Reverse a vector
rev_val = val[::-1]
rev_val

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [11]:
#  Create a 3x3 matrix with values ranging from 0 to 8

mat = np.arange(0,9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
#  Find indices of non-zero elements from [1,2,0,0,4,0]

arr = np.array([1,2,0,0,4,0])
ind = np.where(arr==0)
ind

(array([2, 3, 5]),)

In [20]:
# Create a 3x3x3 array with random values
np.random.seed(2112001)
rand_arr = np.array(np.random.randint(1000,size=9)).reshape(3,3)
rand_arr

array([[871, 823, 504],
       [830, 224, 182],
       [257, 946,  17]])

In [31]:

# Create a 10x10 array with random values and find the minimum and maximum values

np.random.seed(2345678)
mat1 = np.array(np.random.randint(10000,size=100)).reshape(10,10)
print(mat1)
np.max(mat1)

[[1043 5329 6491 2778 4748 7704 3128 1060 1056 3723]
 [3952 1281 3248 7969 1913  333 2678 2315 6086 6074]
 [6475 8138 9189 6377 4735 2422 5484 2481 6022 6679]
 [1244  496  456 1934 1191 6650  218 5252  355 7598]
 [7105 9918 1463 6839 2120 2044 6756 2268 1536 2749]
 [1333 8133 5274 1747 3573 4433  603 2569 3678 4066]
 [2169 7043 8516 9919  161 4584 2113 6051 8268 4516]
 [ 705 8643 5258 5916 1547 6903 8975 1757 9467 6751]
 [8363 6749 7872 8189 2953 8772 4170 2620 7836 8712]
 [5776   35 8939 7766 6819 6720 3108 3542 9370 9883]]


9919

In [29]:
# Create a 2d array with 1 on the border and 0 inside
arrt = np.ones(16).reshape(4,4)
arrt[1:3,1:3]=0
arrt


array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])